version: 2.1

orbs:
  maven: circleci/maven@1.2.0
  docker: circleci/docker@1.7.0

jobs:
  build:
    machine: true
    working_directory: ~/project
    steps:
      - checkout
      - setup_remote_docker
      - docker/install-docker-compose
      - run:
          name: Build Selenium Hub
          command: docker-compose up -d
  test:
    docker:
      - image: cimg/openjdk:15.0
    steps:
      - run:
          name: Run Tests
          command: maven/test